USE [master]
GO

/****** Object:  Database [bnadbTemp]    Script Date: 2021-02-02 22:28:20 ******/
CREATE DATABASE [bnadbTemp]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'bnadbTemp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.WODEVSQL\MSSQL\DATA\bnadbTemp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'bnadbTemp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.WODEVSQL\MSSQL\DATA\bnadbTemp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bnadbTemp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bnadbTemp] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [bnadbTemp] SET ANSI_NULLS OFF
GO

ALTER DATABASE [bnadbTemp] SET ANSI_PADDING OFF
GO

ALTER DATABASE [bnadbTemp] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [bnadbTemp] SET ARITHABORT OFF
GO

ALTER DATABASE [bnadbTemp] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [bnadbTemp] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [bnadbTemp] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [bnadbTemp] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [bnadbTemp] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [bnadbTemp] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [bnadbTemp] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [bnadbTemp] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [bnadbTemp] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [bnadbTemp] SET  DISABLE_BROKER
GO

ALTER DATABASE [bnadbTemp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [bnadbTemp] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [bnadbTemp] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [bnadbTemp] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [bnadbTemp] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [bnadbTemp] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [bnadbTemp] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [bnadbTemp] SET RECOVERY SIMPLE
GO

ALTER DATABASE [bnadbTemp] SET  MULTI_USER
GO

ALTER DATABASE [bnadbTemp] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [bnadbTemp] SET DB_CHAINING OFF
GO

ALTER DATABASE [bnadbTemp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [bnadbTemp] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [bnadbTemp] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [bnadbTemp] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [bnadbTemp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bnadbTemp] SET  READ_WRITE
GO


